### ISSUE TITLE
Add RSS Feed

### ISSUE THREAD

**Issue by drmzio** [OFFLINE-GmbH/octobertricks.com#13]
If possible, would you be able to provide an RSS feed of latest tricks? Asking because I would like to create a dashboard widget that displays the latest tricks. Thanks!

**Comment by tobias-kuendig** [comment]
This is a great idea! Would you be willing to provide a PR with this feature?

We could use one of the existing PHP RSS libraries (like https://github.com/bhaktaraz/php-rss-generator) and just register a route in `routes.php`.

**Comment by tobias-kuendig** [comment]
Done!

https://github.com/OFFLINE-GmbH/octobertricks.com/commit/a7a5611dd8701022816a217d13e3c8d44f711525

https://octobertricks.com/rss
