### ISSUE TITLE
Add support for listing author tricks

### ISSUE THREAD

**Issue by LarryBarker** [OFFLINE-GmbH/octobertricks.com#14]
It may be useful to allow users to find tricks by author. Author names can be linked to a listing of the authors tricks, and individual tricks can have a section to show other tricks by the same author.

**Comment by LarBearrr** [comment]
@tobias-kuendig How is the backend supposed to work? I setup a test account, submitted a trick, and can see it in the Tricks controller. I don't see a way to publish it though? Also tried creating a proposal but am getting an error that the `trick_id` column does not have a default value.

Either I've done something wrong, or don't understand the process for proposing and accepting tricks.

Thanks!

**Comment by LarBearrr** [comment]
See #17
