### ISSUE TITLE
Mobile nav z-index is putting mobile nav behind main content

### ISSUE THREAD

**Issue by LarBearrr** [OFFLINE-GmbH/octobertricks.com#18]
Just noticed this and am not sure how to fix? I tried bumping up the `z-index` to `9999` but it did not work. See below for a screen shot:
![image](https://user-images.githubusercontent.com/28734844/75008945-f72f5000-543e-11ea-961e-c126f6e73311.png)

**Comment by tobias-kuendig** [comment]
We might have to make the header relative and bump up the z-index of it?
