### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/octobertricks.com#4]
Currently, it is not so easy to get this project up and running for development. The process described in the [README](https://github.com/OFFLINE-GmbH/octobertricks.com#development) does not work in the current form, as the bootstrapper will fail with errors, as it cannot run any artisan commands. I debugged this case and appears that this is because of the fact that the `OFFLINE.Tricks` plugin requires `RainLab.User`, which is not available on the first artisan calls. This causes a whole chain of new errors, the first one beeing that the database cannot be migrated, as the env command already errors out.

Next, the project should provide some seed data (tricks, topics, ...), as without this data there are various other errors which prevents developers from using the plugin for development right away.

And a minor note: The trick's topic should be `required` in the backend as well, just as it is required on the frontend form.

**Comment by pvullioud** [comment]
Hi @alxy 
I'm doing a seed command for this project

**Comment by LarBearrr** [comment]
@alxy  Are you still having issues? Just wanted to chime in here and say that I have set this project up successfully, both at the office and at home. I did not see the seeder originally, and had an issue trying to create a test trick. The seeder works great, and is a wonderful example of how to seed large amounts of data, something I have struggled with in previous projects.

@pvullioud I do have questions about how `oc-boostrapper` affects version control. After running `october install` there are a number of files that are now tracked. Obviously I need them locally, but don't want to commit. How do you handle this process?

![image](https://user-images.githubusercontent.com/28734844/75009398-33af7b80-5440-11ea-9b53-736d6284a124.png)

**Comment by tobias-kuendig** [comment]
You can just git reset the files that were modified. Once your .env has been written the rest can be discarded. It's probably because your template files have been copied over the ones in the repo, this are the changes you see.
