### ISSUE TITLE
Avatars aren't loading (correctly)

### ISSUE THREAD

**Issue by SamBrishes** [OFFLINE-GmbH/octobertricks.com#53]
Hello,

I'm not sure what kind of service provider `hello-avatar.com` is (the page itself seems down as well), but it doesn't seem to work.

![hello-avatar](https://user-images.githubusercontent.com/106578633/188620331-df724c28-559b-4b07-933e-bdd37207409d.PNG)

~ Sam.

**Comment by tobias-kuendig** [comment]
Thank you for this report! Unfortunately, this is usually how it goes for those services. The traffic becomes overwhelming if they gain popularity.

We did swtich to hello-avatar.com from another provider a few months ago:
https://github.com/OFFLINE-GmbH/octobertricks.com/pull/33/files

I guess the best solution would be to implement something locally.
